### ISSUE TITLE
A Question about the merit function

### ISSUE THREAD

**Issue by purewater0901** [HJReachability/ilqgames#60]
Hi! Thank you for opening your code to the public and this repository really helps me to understand your paper. I have a question about the merit function in the line search. Currently, it seems the author uses the squared norm of the gradient like below.

https://github.com/HJReachability/ilqgames/blob/5a0554090c79b26455ad69049359478ffbcf5bd8/src/ilq_solver.cpp#L422-L443

So, I wonder why the author uses the value of the squared norm of the gradient instead of the value of the cost function to check the convergence.

**Comment by dfridovi** [comment]
Hi @purewater0901 - thanks so much for your interest and I'm glad the code is useful! To your question, the reason I used the squared gradient norm is because, to solve a *game* rather than an *optimization problem*, we can't just use cost since each player has a different idea of cost. Rather, we treat this as a root finding problem on the KKT systems of all the players concatenated together.

**Comment by purewater0901** [comment]
@DavidMcPherson Thank you for your reply! 

>  the reason I used the squared gradient norm is because, to solve a game rather than an optimization problem, we can't just use cost since each player has a different idea of cost.

To my understanding, if the squared norm of the gradient is zero, then it means the original function of the gradient converges to a certain point(Original function may increase or decrease as you said, but it will converge to a certain point). If so, I feel we can also use the difference of the cost to check the convergence.

**Comment by dfridovi** [comment]
btw I'm @dfridovi - @DavidMcPherson is a colleague of mine. To rephrase my point you highlighted, consider a two player zero sum simple static game where P1 has problem `min_x f(x, y)` and P2 has the problem `min_y -f(x, y)`. What is the single merit function to use here? If you use "the cost", i.e. f(x, y), then any time P1 is happy with a direction `(dx, dy)` then P2 will be unhappy... So to remedy this issue the thing to do is to use the norm of `(\nabla f_x, \nabla -f_y)` as a merit function. Of course, this is immediately problematic in that it has roots at all first order stationary points of the game, which are called "quasi-Nash" equilibria (and not just at Nash equilibria), but it's a good start.

**Comment by purewater0901** [comment]
@dfridovi Sorry, I send the message incorrectly, and thank you for your clarification. I think I got your point and I'll continue to read your code.
