### ISSUE TITLE
question about the class proximity constraint

### ISSUE THREAD

**Issue by zhonghai1995** [HJReachability/ilqgames#64]
Hello Professor Fridovich-Keil, I have a question about the class proximity constraint.  In the implementation of the Quadraticize function of the class proximity constraints, it calls the ModifyDerivatives function. In the ModifyDerivatives function, it calculates the derivatives of lambda g(x) + mu g(x) g(x) / 2.

 However, since the proximity constraint is an inequality constraint, then when the constraint value is less than 0 (the constraint is satified), should we still add the derivate of mu g(x) g(x) / 2?  Because I think for inequality constraints, the augmented lagrangian is L = lambda * g(x) + (mu/2)*max(0,g(x))^2?

**Comment by dfridovi** [comment]
In that case `\mu` will get set to `0`. See here.
https://github.com/HJReachability/ilqgames/blob/d8aad9d2c71b1abdc2dc1f5dce74595ebf4bd928/include/ilqgames/constraint/constraint.h#L112
You're probably right that it could be implemented more efficiently though. Feel free to submit a PR!

**Comment by zhonghai1995** [comment]
Thanks for the quick reply!
