### ISSUE TITLE
Question for variable kOrientedRight

### ISSUE THREAD

**Issue by zhonghai1995** [HJReachability/ilqgames#66]
Hello Professor David, I am trying to make my own example but I am bit confused of the meaning of kOrientedRight variable. Could you please explain a bit about the meaning of kOrientedRight and how to use it? Thanks so much!

static constexpr bool kOrientedRight = true;

**Comment by dfridovi** [comment]
Every `Polyline2` has an orientation - just like any curve (think about the right hand rule). In the code, flags like this are used to flip the orientation of costs and constraints involving `Polyline2`s.

**Comment by zhonghai1995** [comment]
Get it. Thanks again.
