### ISSUE TITLE
Question about linearize function in dynamics header file

### ISSUE THREAD

**Issue by zhonghai1995** [HJReachability/ilqgames#67]
Hello Professor David, 

I have a question about linearizing the dynamics around an operating point. If I understand it correctly, in the dynamics header file, the current implementation of linearize function (e.g., in the unicycle4d) corresponds to using Euler integration, if we use RK4, then maybe we need to provide another version of linearize function? But yes maybe there won't be much difference.

Thanks so much!

**Comment by dfridovi** [comment]
Linearization is separate from time discretization. Linearization is just taking a bunch of derivatives. Time discretization happens separately. You could also do time discretization first (e.g., with Euler or RK), then linearize. Either way.
