### ISSUE TITLE
A typo in feedback LQ Nash derivation pdf

### ISSUE THREAD

**Issue by zhonghai1995** [HJReachability/ilqgames#70]
Hello Professor David,

I think there is a typo in the feedback LQ Nash derivation pdf. On the right-hand side of equation (11), should we also add r_{t}^{ii}? Thanks!

**Comment by dfridovi** [comment]
Very good catch! As it turns out, the implementation here was correct. Not quite sure how this happened, but much obliged for the pointer. Keep them coming!

https://github.com/HJReachability/ilqgames/blob/41c90847f14dd299284190b1591259eafbd3ec23/src/lq_feedback_solver.cpp#L157
