### ISSUE TITLE
question on initial strategy

### ISSUE THREAD

**Issue by tmacattank** [HJReachability/ilqgames#74]
Dear author,
in constructing initial strategies, the code always give zero contro input as follows: 
` virtual void ConstructInitialStrategies() {
        strategies_.reset(new std::vector<Strategy>());
        for (PlayerIndex ii = 0; ii < dynamics_->NumPlayers(); ii++)
            strategies_->emplace_back(time::kNumTimeSteps, dynamics_->XDim(),
                                      dynamics_->UDim(ii));
    }`
while given different initial guess, the results will converge differently. Does it mean that the result given zero control input as initial guess is only local nash equilibruim instead of global.

**Comment by dfridovi** [comment]
Two comments:
1. Please read the paper for more details - as stated there, this algorithm is only looking for local Nash points. The mechanism behind why this is happening is explained in greater detail in the journal version [here](https://epubs.siam.org/doi/pdf/10.1137/21M142530X?casa_token=VObThM6Wdi4AAAAA:8K-cPxjPUrB7lNEGCr9PabJxg2atd0YkMQp0UkIOm1UvoExeYdwRXAlJrJL-XkeNq6oVmtYBwbE).
2. Actually, converging to different solutions from different initializations does not necessarily imply that those solutions are local - they could in fact be global! This is the case in any optimization problem, after all ;)
