### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by git0929** [HJReachability/ilqgames#75]
Hello, I would like to ask, your code can be run, but there is a question, that is, how do you use the dataset to validate, is there a dataset that can be referenced，If so, can you tell me?

**Comment by dfridovi** [comment]
There is no "dataset" here: this is a solver for a class of dynamic games. Please read the paper for further details on validation and experimentation.

**Comment by git0929** [comment]
I'm referring to the Monte Carlo tree that you use to use random number samples without having a separate file, like a dataset，Thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2023年11月28日(星期二) 上午10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HJReachability/ilqgames] Dataset issues (Issue #75)





 
There is no "dataset" here: this is a solver for a class of dynamic games. Please read the paper for further details on validation and experimentation.

**Comment by dfridovi** [comment]
There is no MC _tree_ here. There _is_ a MC experiment in the paper, but I do not recall the exact setup for that experiments. I believe it is somewhere in the [ILQGames.jl](https://github.com/lassepe/iLQGames.jl) repository (which is a Julia implementation of this project), but unfortunately I cannot point you to a specific commit or file. We did not do anything particularly fancy or creative here though: if memory serves, it was just uniform random sampling of some parameter governing a sinusoidal control input for the initial trajectory of each player.

**Comment by git0929** [comment]
Thank you for your reply. I'll check it out again.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2023年11月28日(星期二) 中午11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HJReachability/ilqgames] Dataset issues (Issue #75)






没有MC树给你。在那里是本文中的MC实验，但我不记得实验的具体设置。我相信它就在ILQGames.jl存储库（这是一个朱莉娅实现这个项目），但不幸的是，我不能指向你一个特定的提交或文件。我们并没有做任何特别花哨或创造性的事情：如果没有记错的话，这只是一个控制每个玩家初始轨迹的正弦控制输入的参数的均匀随机抽样。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:< HJ 可及性/游戏/问题/ 75 / ***@***.***和&gt;
